# Setup
title: Jiao Zhao
description: Applied Geoinformatics, University of Salzburg
url: https://superjiojio.github.io/
avatar: /me.jpg
paginate: 5
permalink: pretty
cover_image: /bg.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: Jiao Zhao
  card: summary
logo: logo.png
social:
  name: Jiao Zhao
  links:
    - https://twitter.com/
    - https://superjiojio.github.io/
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Yanxiang Wang
  url: https://github.com/anganiang
  email: yanxiang.wang@stud.sbg.ac.at
